### ISSUE TITLE
Add resource to create secrets

### ISSUE THREAD

**Issue by tboerger** [cyberark/terraform-provider-conjur#116]
## Is your feature request related to a problem? Please describe.

I would like to be able to create secrets with Terraform.

## Describe the solution you would like

Create a new resource to create secrets with a policy via Terraform.

## Describe alternatives you have considered

Currently we are hacking a similar solution based on a shell script used within a null_resource local-exec resource which feels pretty wrong.

## Additional context

None

**Comment by bocan** [comment]
Possibly bad form but I'm gonna +1 this.  I work in a Banking environment and for reasons that still escape me, our Cyberark is behind a cursed Citrix environment, causing most people to not want to use it.  You think, that's ok, I'll use Terraform to create and read my secrets - then you find this half built Terraform provider.  I'm ready to just use AWS secrets provider instead...
