### ISSUE TITLE
This provider should be doc'ed on conjur.org

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/terraform-provider-conjur#19]
We should probably just explain it briefly and link to project README.

**Comment by perrygold** [comment]
Word Doc for commenting:
https://cyberark365.sharepoint.com/:w:/s/Conjur/EYOwOvkLKB5NqtuH9OxcHCsBOcv9uwb05j0-Senpo2tiXw?e=yyjKFz

**Comment by ismarc** [comment]
The docs have been published.
