### ISSUE TITLE
in documentation, need to add "terraform init" step for plugin installation

### ISSUE THREAD

**Issue by jodyhuntatx** [cyberark/terraform-provider-conjur#22]
The documentation (`Readme.md`), does not mention that users will need to run `terraform init` to initialize their Terraform project.  

**Expected Behavior**
All instructions to initialize and execute a Terraform run are present in the documentation, so readers do not become confused.

**Comment by sgnn7** [comment]
Closing via https://app.zenhub.com/workspace/o/cyberark/terraform-provider-conjur/issues/55
