### ISSUE TITLE
Take the output example out of documentation

### ISSUE THREAD

**Issue by brettswan** [cyberark/terraform-provider-conjur#23]
```
output "dbpass_output" {
  value = "${data.conjur_secret.dbpass.value}"
  sensitive = true  # toggle this off to view value
}
``` 

When used in a remote state environment this will write your secret out to a state file in plaintext. In the documentation there should at least be a disclaimer around this warning people not to do this.

**Comment by sgnn7** [comment]
Closed via https://github.com/cyberark/terraform-provider-conjur/pull/55
