### ISSUE TITLE
Terraform v0.12.0 - Incompatible API version with plugin

### ISSUE THREAD

**Issue by quincycheng** [cyberark/terraform-provider-conjur#26]
The provider doesn't work with Terraform v0.12.0
Error message after "terraform apply":

_Error: Failed to instantiate provider "conjur" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]_

**Comment by brikelly** [comment]
The fix is to update our dependencies to the v12 version of the Terraform SDK: https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#upgrading-to-the-latest-terraform-sdk

**Comment by jralmaraz** [comment]
Hi,

Unfortunately, facing the same here, will watch this issue for an update.

oauth-app joalmaraz$ terraform-0.12.2 plan

Error: Failed to instantiate provider "conjur" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

**Comment by AndrewCopeland** [comment]
Hasn't this been resolved in:
https://github.com/cyberark/terraform-provider-conjur/commit/d72a2cd2060f8ab24cf21b2084b04f17c634455d

However the latest compiled binary is not available in Releases and needs to be added.

**Comment by quincycheng** [comment]
Is this repo being maintained?  
Can anyone release an updated version with the patch?
The latest version was released in 2018 Aug and it is in 2020 now.
Thanks in advance.

**Comment by sgnn7** [comment]
Newly-released `v0.3.0` should fix this. You can find it at https://github.com/cyberark/terraform-provider-conjur/releases/tag/v0.3.0. Homebrew recipe has been updated too.

Please reopen this issue if there are any further problems with this.
