### ISSUE TITLE
New Terraform version has been released

### ISSUE THREAD

**Issue by garkler** [cyberark/terraform-provider-conjur#28]
@Andrew.Copeland has made some changes to our terraform provider in order to support the new version of terraform that came out.

The objective of this card is :
1. To ensure all changes are in
2. To release the binaries of the provider

Also see 
https://github.com/cyberark/terraform-provider-conjur/issues/26

**Comment by jralmaraz** [comment]
Waiting on this as some of the other providers used already upgraded and Conjur has been the only one which is not compatible (so enforcing baseline version :( ).

Cheers.

**Comment by sgnn7** [comment]
Closed with release v0.3.0: https://github.com/cyberark/terraform-provider-conjur/releases/tag/v0.3.0.
