### ISSUE TITLE
No version is available

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/terraform-provider-conjur#30]
## Issue description
This provider does not include any version information.  This makes validating which version you have very problematic.

## Steps to reproduce the issue
1. View Terraform version:
    ```
    $ terraform version
    ```
## What's the expected result?
Output would look something like:
```
Terraform v0.12.1
+ provider.conjur v0.2
```
## What's the actual result?
```
Terraform v0.12.1
+ provider.conjur (unversioned)
```

**Comment by sgnn7** [comment]
This seems to be a file naming issue. We just need to append `_v<semver` to the name of the plugin during installation but it requires some doc/brew/goreleaser changes.

**Comment by sgnn7** [comment]
Closing via https://app.zenhub.com/workspace/o/cyberark/terraform-provider-conjur/issues/55
