### ISSUE TITLE
Recompile provider and test to prepare for new release

### ISSUE THREAD

**Issue by izgeri** [cyberark/terraform-provider-conjur#43]
A new release of Terraform came out, but our current plugin doesn’t work with it.

AC:
- [ ] Recompile our provider, and verify that it works with the latest release of Terraform
- [ ] If the previous step is complete, add a commit with an updated CHANGELOG and version number for our provider to facilitate a new release

Any additional easy work to improve this project, including improved test coverage or improved documentation, would also be appreciated.

**Comment by sgnn7** [comment]
Closed with #46 and [v0.3.0 release](https://github.com/cyberark/terraform-provider-conjur/releases/tag/v0.3.0).
