### ISSUE TITLE
Is there a way to avoid the secrets ending up in state files?

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/terraform-provider-conjur#6]
Context: https://github.com/hashicorp/terraform/issues/516

**Comment by dustinmm80** [comment]
After much investigation and trial and error, no Terraform is not helpful when you want to keep your secrets out of state files. HashiCorp provides no solution, and I didn't see any in the community.

We *could* do more investigation and see if we can come up with a more secure Terraform state workflow, using Conjur for encryption keys or something, but I don't think we should tackle that now.

Closing this issue, we'll create another if we need it.

**Comment by monkey-jeff** [comment]
Just another +1 here. I recently opened https://github.com/terraform-providers/terraform-provider-azurerm/pull/2402 to try an remedy this for an service principal in azure by hashing the stored password.
