### ISSUE TITLE
Publish the provider on registry.terraform.io

### ISSUE THREAD

**Issue by Lunik** [cyberark/terraform-provider-conjur#72]
## Is your feature request related to a problem? Please describe.

Terraform providers are now easily downlodable through official [Terraform registry](https://registry.terraform.io)

It could allow simple installation as follow : 

```hcl
terraform {
  required_providers {
    conjur = {
      source  = "cyberark/conjur"
      version = "~> 0.4"
    }
  }
}
```

## Describe the solution you would like

Publicsh the provider following the [Terraform documentation](https://www.terraform.io/docs/registry/providers/publishing.html) about publishing provider to the Terraform registry.

## Describe alternatives you have considered

Manually download the provider and put it in the right directory before execution. But it's a pain to maintain and required additional dependencies like `curl`/`wget`/`tar`

## Additional context

N/A

**Comment by izgeri** [comment]
Thanks for this suggestion @Lunik! It sounds like a great idea, so I'll work with my product team to get this scheduled for sometime in 2021. I'll try to update back here once I have a better idea of the exact timeline ... stay tuned!

**Comment by Lunik** [comment]
Hello, any update or ETA ?

**Comment by boazmichaely** [comment]
Published in [Aha ideas](https://cyberark.aha.io/ideas/ideas/SCR-I-81)

**Comment by jonharrisnm** [comment]
Any status on this?

**Comment by izgeri** [comment]
Tagging in @alexkalish, who may have more up-to-date information.

**Comment by alexkalish** [comment]
@jonharrisnm: Thanks for checking in.  I've asked our product manager for an update and hope to hear soon.

**Comment by nehrman** [comment]
Do you have any news on this one?

**Comment by mcfisch** [comment]
This is available now (thanks!), but the documentation still doesn't reflect it.
